version: 2

models:
  - name: sl_orders
    description: "Silver layer for orders data"
    columns:
      - name: order_id
        description: "The unique identifier for each order"
        tests:
          - unique
          - not_null
      - name: customerID
        description: "Identifier for the user who placed the order"
        tests:
          - not_null
      - name: status
        description: "Status of the order"
        tests:
          - not_null
      - name: gender
        description: "Gender information of the user"
        tests:
          - not_null
      - name: created_at
        description: "Date when the order was created"
        tests:
          - not_null
      - name: returned_at
        description: "Date when the order was returned"
      - name: shipped_at
        description: "Date when the order was shipped"
      - name: delivered_at
        description: "Date when the order was delivered"
      - name: time_to_ship
        description: "Time taken to ship the order"
      - name: time_to_deliver
        description: "Time taken to deliver the order"
      - name: costPrice
        description: "Total cost price of the order"
        tests:
          - not_null
      - name: totalRetailPrice
        description: "Total retail price of the order"
        tests:
          - not_null
      - name: isDelivered
        description: "Flag indicating if the order was delivered"
        tests:
          - not_null
      - name: isShipped
        description: "Flag indicating if the order was shipped"
        tests:
          - not_null
      - name: isReturned
        description: "Flag indicating if the order was returned"
        tests:
          - not_null

  - name: sl_products
    description: "Silver layer for products data"
    columns:
      - name: id
        description: "The unique identifier for each product"
        tests:
          - unique
          - not_null
      - name: cost
        description: "Cost of the product"
        tests:
          - not_null
      - name: category
        description: "Category to which the product belongs"
        tests:
          - not_null
      - name: name
        description: "Name of the product"
        
      - name: brand
        description: "Brand of the product"
        
      - name: retail_price
        description: "Retail price of the product"
        tests:
          - not_null
      - name: department
        description: "Department to which the product belongs"
        tests:
          - not_null
      - name: sku
        description: "Stock Keeping Unit (SKU) of the product"
        tests:
          - not_null
      - name: distribution_center_name
        description: "Name of the distribution center associated with the product"
        tests:
          - not_null
      - name: distribution_center_latitude
        description: "Latitude coordinate of the distribution center"
        tests:
          - not_null
      - name: distribution_center_longitude
        description: "Longitude coordinate of the distribution center"
        tests:
          - not_null

  - name: sl_users
    description: "Silver layer for users data"
    columns:
      - name: customerID
        description: "The unique identifier for each user"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the user"
        tests:
          - not_null
      - name: last_name
        description: "Last name of the user"
        tests:
          - not_null
      - name: email
        description: "Email address of the user"
        tests:
          - not_null
      - name: age
        description: "Age of the user"
        tests:
          - not_null
      - name: gender
        description: "Gender of the user"
        tests:
          - not_null
      - name: state
        description: "State where the user is located"
        tests:
          - not_null
      - name: street_address
        description: "Street address of the user"
        tests:
          - not_null
      - name: postal_code
        description: "Postal code of the user"
        tests:
          - not_null
      - name: city
        description: "City where the user is located"
        tests:
          - not_null
      - name: country
        description: "Country where the user is located"
        tests:
          - not_null
      - name: latitude
        description: "Latitude coordinate of the user"
        tests:
          - not_null
      - name: longitude
        description: "Longitude coordinate of the user"
        tests:
          - not_null
      - name: traffic_source
        description: "Source of the traffic leading to the user"
        tests:
          - not_null
      - name: created_date
        description: "Date when the user account was created"
        tests:
          - not_null
      - name: created_timestamp
        description: "Timestamp when the user account was created"
        tests:
          - not_null
